---
linters-settings:
  errcheck:
    exclude: ./.errcheck_excludes.txt
  misspell:
    locale: "US"

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - errcheck
    - gocritic
    - goimports
    - golint
    - gosimple
    - govet
    - ineffassign
    - misspell
    - prealloc
    - rowserrcheck
    - scopelint
    - staticcheck
    - structcheck
    - typecheck
    - unparam
    - unused
    - varcheck
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - scopelint
        - errcheck
    - linters:
        - gosec
      text: "G401:"
