---
linters:
  presets:
    - bugs
    - error
    - import
    - metalinter
    - module
    - unused

  enable:
    - testifylint

  disable:
    # preset error
    - err113 # Very annoying to define static errors everywhere
    - wrapcheck # Very annoying to wrap errors everywhere
    # preset import
    - depguard

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/hetznercloud)

  exhaustive:
    # Switch cases with a default case should be exhaustive.
    default-signifies-exhaustive: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
    - path: testing\.go
      text: unused-parameter
    - linters:
        - testifylint
      text: bool-compare
    - linters:
        - testifylint
      text: empty

      # Can be removed once we migrated to the plugin framework.
    - linters:
        - errcheck
      text: Error return value of `d.Set` is not checked
