---
linters-settings:
  errcheck:
    exclude-functions:
      - (*github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.ResourceData).Set
  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    - gofmt
    - bodyclose
    - errcheck
    - exportloopref
    - gocritic
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - prealloc
    - revive
    - rowserrcheck
    - staticcheck
    - typecheck
    - unparam
    - unused
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - exportloopref
        - gosec
        - errcheck
    - path: testing\.go
      text: unused-parameter
